version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - echo prebuild
      - npm run prebuild
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the React code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync build/ "s3://${BUCKET_NAME}" --delete --exclude 'build/index.html' --exclude 'build/*' --metadata-directive REPLACE --cache-control public,max-age=604800,s-maxage=86400
      - aws s3 sync build/ "s3://${BUCKET_NAME}" --exclude='*' --include='build/*' --metadata-directive REPLACE --cache-control public,max-age=0,s-maxage=600 --content-type application/json
      - aws s3 sync build/ "s3://${BUCKET_NAME}" --exclude='*' --include='build/index.html' --metadata-directive REPLACE --cache-control public,max-age=0,s-maxage=600 --content-type text/html
      - echo Files Uploaded to S3
