version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - echo prebuild
      - npm run prebuild

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the React code
      - npm run "${BUILD_ENV}"


  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync build/ "s3://${BUCKET_NAME}"
      - echo Files Uploaded to S3
